import { Inter, Syne } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import 'animate.css';
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const syne = Syne({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800"] });

export const metadata = {
  title: "Harmony Entertainment",
  icons: {
    icon: '/assets/hcf-logo.jpg'
  }
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/assets/hcf-logo.jpg'/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      <body className={syne.className}>
        <div className="w-full fixed top-0 z-[9999]">
          {/* <Navbar /> */}
        </div>
        <div className="">
          {children}
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
